# Generated by Django 5.1.6 on 2025-02-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesdata',
            name='category',
            field=models.CharField(default='movies-category', max_length=200),
        ),
    ]
